"""MAXTUI type stubs for IDE autocomplete"""

from typing import List, Optional, Tuple, Any

__version__: str

class App:
    def __init__(self) -> None: ...
    def set_fps(self, fps: int) -> App: ...
    def set_theme(self, name: str) -> App: ...
    def add_widget(self, widget: Any) -> App: ...
    def stop(self) -> None: ...
    def run(self) -> None: ...

class Paragraph:
    def __init__(self, text: str) -> None: ...
    def set_text(self, text: str) -> None: ...

class Button:
    def __init__(self, label: str) -> None: ...
    def set_focused(self, focused: bool) -> None: ...

class Input:
    def __init__(self, placeholder: str) -> None: ...
    def get_value(self) -> str: ...
    def set_value(self, value: str) -> None: ...
    def set_focused(self, focused: bool) -> None: ...

class Gauge:
    def __init__(self, label: str, percent: float) -> None: ...
    def set_percent(self, percent: float) -> None: ...

class List:
    def __init__(self, title: str) -> None: ...
    def add_item(self, item: str) -> None: ...
    def select_next(self) -> None: ...
    def select_prev(self) -> None: ...
    def selected(self) -> int: ...

class Table:
    def __init__(self, title: str) -> None: ...
    def add_row(self, row: List[str]) -> None: ...
    def select_row(self, row: int) -> None: ...

class Chart:
    def __init__(self, title: str) -> None: ...
    def add_point(self, x: float, y: float) -> None: ...

class Divider:
    def __init__(self) -> None: ...

class Modal:
    def __init__(self, title: str, content: str) -> None: ...
    def width_percent(self, w: int) -> Modal: ...

class Spinner:
    def __init__(self, label: str) -> None: ...
    def advance(self) -> None: ...

class Layout:
    @staticmethod
    def vertical() -> Layout: ...
    @staticmethod
    def horizontal() -> Layout: ...
    def set_margin(self, v: int, h: int) -> None: ...
    def set_spacing(self, s: int) -> None: ...

class Constraint:
    @staticmethod
    def fixed(size: int) -> Any: ...
    @staticmethod
    def percentage(p: int) -> Any: ...
    @staticmethod
    def fill() -> Any: ...

class Color:
    @staticmethod
    def red() -> Any: ...
    @staticmethod
    def green() -> Any: ...
    @staticmethod
    def blue() -> Any: ...
    @staticmethod
    def white() -> Any: ...
    @staticmethod
    def black() -> Any: ...
    @staticmethod
    def rgb(r: int, g: int, b: int) -> Any: ...

class Style:
    def __init__(self) -> None: ...
    def fg(self, color: Any) -> Style: ...
    def bg(self, color: Any) -> Style: ...
    def bold(self) -> Style: ...
    def italic(self) -> Style: ...

class Theme:
    @staticmethod
    def dark() -> Any: ...
    @staticmethod
    def light() -> Any: ...
    @staticmethod
    def monokai() -> Any: ...

class TextAnimation:
    @staticmethod
    def typewriter(interval_ms: int) -> Any: ...
    @staticmethod
    def scroll_left(speed: int) -> Any: ...

class FrameAnimation:
    def __init__(self, frames: List[str], interval_ms: int) -> None: ...
    def get_current_frame(self) -> Optional[str]: ...
    def next_frame(self) -> None: ...
    def reset(self) -> None: ...

class Effect:
    @staticmethod
    def fade(duration_ms: int) -> Any: ...
    @staticmethod
    def slide(duration_ms: int) -> Any: ...
    @staticmethod
    def blink(interval_ms: int) -> Any: ...
    @staticmethod
    def pulse(duration_ms: int) -> Any: ...

class EffectManager:
    def __init__(self) -> None: ...
    def add_effect(self, effect: Any) -> None: ...
